const repoNames = [
    'fake-node-core',
    'generate-id',
    'i-insula',
    'meta-node',
    'ndx-cli',
    'ndx-native',
    'node-biometrics',
    'node-biosensors',
    'node-biosignal-processing',
    'node-causality',
    'node-lsl',
    'node-mangled-names',
    'node-neuropype',
    'node-osf',
    'node-robotic-arm',
    'node-runtime-monitors',
    'node-server-plots',
    'node-signal-processing',
    'node-task-queue',
    'node-tdd',
    'node-test-counter',
    'node-wifi-connector',
    'node-xdf',
    'personomic',
    'react-biosensors',
    'react-connectivity-graphs',
    'react-github-badge',
]

export default repoNames
